# Generated by Django 6.0 on 2026-05-23 09:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_is_blocked"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="blocked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="blocked_reason",
            field=models.TextField(blank=True, null=True),
        ),
    ]
