# Generated by Django 6.0.4 on 2026-05-08 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
