# Generated by Django 6.0.4 on 2026-05-11 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0004_submission'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='test_cases',
            field=models.JSONField(default=list),
        ),
    ]
