# Generated by Django 6.0.4 on 2026-05-11 08:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0005_challenge_test_cases'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='function_name',
            field=models.CharField(default='solution', max_length=100),
        ),
    ]
