# Generated by Django 6.0.4 on 2026-05-11 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0006_challenge_function_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='function_name',
        ),
        migrations.AlterField(
            model_name='challenge',
            name='difficulty',
            field=models.CharField(choices=[('EASY', 'Easy'), ('MEDIUM', 'Medium'), ('HARD', 'Hard')], max_length=20),
        ),
    ]
