# Generated by Django 6.0.4 on 2026-05-12 06:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0007_remove_challenge_function_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='room',
            old_name='time_limit',
            new_name='time_limit_minutes',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='test_cases',
        ),
        migrations.AddField(
            model_name='challenge',
            name='function_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='language',
            field=models.CharField(choices=[('PYTHON', 'Python')], default='PYTHON', max_length=20),
        ),
        migrations.AddField(
            model_name='challenge',
            name='memory_limit_mb',
            field=models.IntegerField(default=128),
        ),
        migrations.AddField(
            model_name='challenge',
            name='time_limit_seconds',
            field=models.IntegerField(default=2),
        ),
        migrations.AddField(
            model_name='challenge',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='room',
            name='ended_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='roomparticipant',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='roomparticipant',
            name='score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='memory',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='passed_testcases',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='submission',
            name='runtime',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='submission',
            name='total_testcases',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='submission',
            name='language',
            field=models.CharField(choices=[('PYTHON', 'Python')], default='PYTHON', max_length=30),
        ),
        migrations.AlterField(
            model_name='submission',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submissions', to='rooms.room'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('CORRECT', 'Correct'), ('WRONG', 'Wrong'), ('ERROR', 'Error')], default='PENDING', max_length=20),
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.TextField()),
                ('expected_output', models.TextField()),
                ('is_hidden', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_cases', to='rooms.challenge')),
            ],
        ),
    ]
