# Generated by Django 6.0.4 on 2026-05-12 09:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0008_rename_time_limit_room_time_limit_minutes_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContestChallenge',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=1)),
                ('points', models.IntegerField(default=100)),
                ('challenge', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='rooms.challenge')),
                ('room', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contest_challenges', to='rooms.room')),
            ],
        ),
    ]
