# Generated by Django 6.0 on 2026-05-20 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rooms', '0010_room_max_participants_room_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='roomparticipant',
            name='tab_switch_count',
            field=models.IntegerField(default=0),
        ),
    ]
