from django.urls import path
from .views import (
    AdminUsersListView,
    AdminPlatformStatsView,
    ChallengeListView,
    UpdateChallengeView,
    CreateChallengeView,
    DeleteChallengeView,
    ChallengeTestCaseListView,
    AddTestCaseView,
    DeleteTestCaseView,
    AdminRoomListView,
    DeleteRoomView,
    EndRoomView,
    AdminRoomDetailView,
    AdminRoomSubmissionsView,
    KickParticipantView,
    AdminAllSubmissionsView,
    BlockUserView,
    UnblockUserView,
)
urlpatterns = [
    path("users/", AdminUsersListView.as_view()),
    path("stats/", AdminPlatformStatsView.as_view()),
    path("platform-stats/", AdminPlatformStatsView.as_view()),
    path("challenges/", ChallengeListView.as_view()),
    path("challenges/create/", CreateChallengeView.as_view()),
    path("challenges/<int:pk>/update/", UpdateChallengeView.as_view()),
    path("challenges/<int:pk>/delete/", DeleteChallengeView.as_view()),
    path("challenges/<int:challenge_id>/testcases/", ChallengeTestCaseListView.as_view()),
    path("challenges/<int:challenge_id>/add-testcase/", AddTestCaseView.as_view()),
    path("testcases/<int:testcase_id>/", DeleteTestCaseView.as_view()),
    path("rooms/", AdminRoomListView.as_view()),
    path("rooms/<int:room_id>/delete/", DeleteRoomView.as_view()),
    path("rooms/<int:room_id>/end/", EndRoomView.as_view()),
    path("rooms/<int:room_id>/", AdminRoomDetailView.as_view()),
    path("rooms/<int:room_id>/submissions/", AdminRoomSubmissionsView.as_view()),
    path("rooms/<int:room_id>/participants/<int:participant_id>/kick/",KickParticipantView.as_view()),
    path("submissions/", AdminAllSubmissionsView.as_view()),
    path("users/<int:user_id>/block/", BlockUserView.as_view()),
    path("users/<int:user_id>/unblock/", UnblockUserView.as_view()),
]
